version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: docker/run-client/Dockerfile
      target: dev
    ports:
      - "3000:3000"
    tty: true # docker run -t
    volumes:
      - ./src:/usr/src/app/src
  cors:
    build: "docker/cors-proxy"
    ports:
      - "9999:9999"
